export const DEFAULT_ROLES = [
  {
    name: "Super Admin",
    slug: "super-admin",
    description: "Full access to all features",
    permissions: ["*"],
    isSystem: true,
  },
  {
    name: "Admin",
    slug: "admin",
    description: "Administrative access",
    permissions: [
      "users:view",
      "users:create",
      "users:edit",
      "users:delete",
      "roles:view",
      "roles:create",
      "roles:edit",
      "roles:delete",
      "products:view",
      "products:create",
      "products:edit",
      "products:delete",
      "categories:view",
      "categories:create",
      "categories:edit",
      "categories:delete",
      "blog:view",
      "blog:create",
      "blog:edit",
      "blog:delete",
      "blog:publish",
      "orders:view",
      "orders:manage",
      "invoices:view",
      "invoices:create",
      "invoices:manage",
      "projects:view",
      "projects:create",
      "projects:edit",
      "projects:delete",
      "crm:view",
      "crm:leads",
      "crm:clients",
      "crm:inquiries",
      "hosting:view",
      "hosting:manage",
      "domains:view",
      "domains:manage",
      "support:view",
      "support:manage",
      "settings:view",
      "settings:manage",
      "analytics:view",
      "ai:access",
      "ai:manage",
      "marketing:view",
      "marketing:manage",
      "google:analytics:view",
      "google:analytics:manage",
      "google:search_console:view",
      "google:search_console:manage",
      "google:business_profile:view",
      "google:business_profile:manage",
      "google:merchant:view",
      "google:merchant:manage",
      "google:ads:view",
      "google:ads:manage",
      "seo:view",
      "seo:manage",
      "seo:sitemap:manage",
      "seo:robots:manage",
      "tracking:view",
      "tracking:manage",
    ],
    isSystem: true,
  },
  {
    name: "Manager",
    slug: "manager",
    description: "Management access",
    permissions: [
      "products:view",
      "products:create",
      "products:edit",
      "blog:view",
      "blog:create",
      "blog:edit",
      "blog:publish",
      "orders:view",
      "orders:manage",
      "invoices:view",
      "projects:view",
      "projects:create",
      "projects:edit",
      "crm:view",
      "crm:leads",
      "crm:clients",
      "crm:inquiries",
      "support:view",
      "support:manage",
      "analytics:view",
      "marketing:view",
      "google:analytics:view",
      "google:search_console:view",
      "seo:view",
      "tracking:view",
    ],
    isSystem: true,
  },
  {
    name: "Staff",
    slug: "staff",
    description: "Basic staff access",
    permissions: [
      "products:view",
      "blog:view",
      "blog:create",
      "orders:view",
      "projects:view",
      "crm:view",
      "crm:inquiries",
      "support:view",
    ],
    isSystem: true,
  },
  {
    name: "Customer",
    slug: "customer",
    description: "Customer access",
    permissions: [
      "orders:view",
      "projects:view",
      "support:view",
    ],
    isSystem: true,
  },
];
