import mongoose from "mongoose";
import DomainTLD from "../models/domain-tld";
import HostingPlan from "../models/hosting-plan";

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/wall-v";

const MARGIN_GENERIC = 15;
const MARGIN_CCTLD = 0;

function applyMargin(price: number, margin: number): number {
  return Math.round(price * (1 + margin / 100) * 100) / 100;
}

function isCCTLD(tld: string): boolean {
  const ccTLDs = [
    "uk", "co.uk", "me.uk", "org.uk",
    "eu", "de", "fr", "it", "es", "nl", "be", "at", "ch", "se", "no", "fi", "dk", "pt", "pl", "gr", "ie",
    "us", "ca", "com.au", "net.au", "org.au", "co.nz", "net.nz", "org.nz",
    "com.cn", "net.cn", "org.cn", "com.tw", "net.tw", "com.hk",
    "co.jp", "co.in", "co.za", "com.mx", "com.br", "com.sg",
    "tv", "cc", "ws", "asia",
  ];
  return ccTLDs.includes(tld);
}

const domainTLDs = [
  // Generic TLDs
  { tld: "com", registrationPrice: 13.50, renewalPrice: 13.50, category: "generic", description: "The most popular domain extension" },
  { tld: "net", registrationPrice: 14.00, renewalPrice: 14.00, category: "generic", description: "Network infrastructure" },
  { tld: "org", registrationPrice: 14.50, renewalPrice: 14.50, category: "generic", description: "Organizations and non-profits" },
  { tld: "info", registrationPrice: 4.49, renewalPrice: 25.50, category: "generic", description: "Informational websites", isPromo: true, promoDuration: 1 },
  { tld: "biz", registrationPrice: 20.00, renewalPrice: 20.00, category: "generic", description: "Business websites" },
  { tld: "name", registrationPrice: 14.00, renewalPrice: 14.00, category: "generic", description: "Personal names" },

  // New TLDs
  { tld: "xyz", registrationPrice: 16.00, renewalPrice: 16.00, category: "new", description: "Creative and innovative brands" },
  { tld: "online", registrationPrice: 9.99, renewalPrice: 33.00, category: "new", description: "Online presence", isPromo: true, promoDuration: 1 },
  { tld: "site", registrationPrice: 6.99, renewalPrice: 33.00, category: "new", description: "Website projects", isPromo: true, promoDuration: 1 },
  { tld: "tech", registrationPrice: 10.99, renewalPrice: 56.50, category: "new", description: "Technology companies", isPromo: true, promoDuration: 1 },
  { tld: "store", registrationPrice: 10.99, renewalPrice: 49.00, category: "new", description: "E-commerce stores", isPromo: true, promoDuration: 1 },
  { tld: "online", registrationPrice: 9.99, renewalPrice: 33.00, category: "new", description: "Online businesses", isPromo: true, promoDuration: 1 },
  { tld: "space", registrationPrice: 5.99, renewalPrice: 30.00, category: "new", description: "Creative portfolios", isPromo: true, promoDuration: 1 },
  { tld: "website", registrationPrice: 5.99, renewalPrice: 25.00, category: "new", description: "Websites", isPromo: true, promoDuration: 1 },
  { tld: "mobi", registrationPrice: 5.99, renewalPrice: 47.00, category: "new", description: "Mobile websites", isPromo: true, promoDuration: 1 },
  { tld: "club", registrationPrice: 22.00, renewalPrice: 22.00, category: "new", description: "Clubs and communities" },
  { tld: "fun", registrationPrice: 6.99, renewalPrice: 36.00, category: "new", description: "Fun and entertainment", isPromo: true, promoDuration: 1 },
  { tld: "ninja", registrationPrice: 12.49, renewalPrice: 29.00, category: "new", description: "Expert professionals" },
  { tld: "solutions", registrationPrice: 8.99, renewalPrice: 29.00, category: "new", description: "Solution providers" },
  { tld: "services", registrationPrice: 11.49, renewalPrice: 36.00, category: "new", description: "Service businesses" },
  { tld: "news", registrationPrice: 11.49, renewalPrice: 30.00, category: "new", description: "News websites" },
  { tld: "company", registrationPrice: 20.00, renewalPrice: 20.00, category: "new", description: "Company websites" },
  { tld: "party", registrationPrice: 27.00, renewalPrice: 27.00, category: "new", description: "Party planning" },
  { tld: "deals", registrationPrice: 36.00, renewalPrice: 36.00, category: "new", description: "Deals and discounts" },
  { tld: "family", registrationPrice: 36.00, renewalPrice: 36.00, category: "new", description: "Family websites" },
  { tld: "press", registrationPrice: 10.99, renewalPrice: 71.00, category: "new", description: "Press and media", isPromo: true, promoDuration: 1 },
  { tld: "pro", registrationPrice: 2.99, renewalPrice: 25.50, category: "new", description: "Professionals", isPromo: true, promoDuration: 1 },
  { tld: "top", registrationPrice: 14.00, renewalPrice: 14.00, category: "new", description: "Top websites" },
  { tld: "icu", registrationPrice: 9.99, renewalPrice: 9.99, category: "new", description: "Short and memorable" },

  // Country-code TLDs
  { tld: "co", registrationPrice: 34.00, renewalPrice: 34.00, category: "cctld", description: "Colombia (great .com alternative)" },
  { tld: "me", registrationPrice: 8.99, renewalPrice: 18.00, category: "cctld", description: "Montenegro (personal sites)" },
  { tld: "tv", registrationPrice: 34.00, renewalPrice: 34.00, category: "cctld", description: "Tuvalu (media and video)" },
  { tld: "cc", registrationPrice: 12.00, renewalPrice: 12.00, category: "cctld", description: "Cocos Islands" },
  { tld: "ws", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Samoa (website)" },
  { tld: "uk", registrationPrice: 7.95, renewalPrice: 7.95, category: "cctld", description: "United Kingdom" },
  { tld: "co.uk", registrationPrice: 7.95, renewalPrice: 7.95, category: "cctld", description: "United Kingdom Commercial" },
  { tld: "org.uk", registrationPrice: 7.95, renewalPrice: 7.95, category: "cctld", description: "United Kingdom Organizations" },
  { tld: "me.uk", registrationPrice: 7.95, renewalPrice: 7.95, category: "cctld", description: "United Kingdom Personal" },
  { tld: "eu", registrationPrice: 7.50, renewalPrice: 7.50, category: "cctld", description: "European Union" },
  { tld: "de", registrationPrice: 12.00, renewalPrice: 12.00, category: "cctld", description: "Germany" },
  { tld: "fr", registrationPrice: 12.00, renewalPrice: 12.00, category: "cctld", description: "France" },
  { tld: "it", registrationPrice: 12.00, renewalPrice: 12.00, category: "cctld", description: "Italy" },
  { tld: "es", registrationPrice: 12.00, renewalPrice: 12.00, category: "cctld", description: "Spain" },
  { tld: "nl", registrationPrice: 12.00, renewalPrice: 12.00, category: "cctld", description: "Netherlands" },
  { tld: "be", registrationPrice: 10.00, renewalPrice: 10.00, category: "cctld", description: "Belgium" },
  { tld: "at", registrationPrice: 14.00, renewalPrice: 14.00, category: "cctld", description: "Austria" },
  { tld: "ch", registrationPrice: 14.00, renewalPrice: 14.00, category: "cctld", description: "Switzerland" },
  { tld: "se", registrationPrice: 20.00, renewalPrice: 20.00, category: "cctld", description: "Sweden" },
  { tld: "no", registrationPrice: 18.00, renewalPrice: 18.00, category: "cctld", description: "Norway" },
  { tld: "fi", registrationPrice: 16.00, renewalPrice: 16.00, category: "cctld", description: "Finland" },
  { tld: "dk", registrationPrice: 18.00, renewalPrice: 18.00, category: "cctld", description: "Denmark" },
  { tld: "pt", registrationPrice: 18.00, renewalPrice: 18.00, category: "cctld", description: "Portugal" },
  { tld: "pl", registrationPrice: 14.00, renewalPrice: 14.00, category: "cctld", description: "Poland" },
  { tld: "gr", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Greece" },
  { tld: "ie", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Ireland" },
  { tld: "us", registrationPrice: 9.00, renewalPrice: 9.00, category: "cctld", description: "United States" },
  { tld: "ca", registrationPrice: 18.50, renewalPrice: 18.50, category: "cctld", description: "Canada" },
  { tld: "com.au", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Australia Commercial" },
  { tld: "net.au", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Australia Network" },
  { tld: "org.au", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Australia Organizations" },
  { tld: "co.nz", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "New Zealand Commercial" },
  { tld: "net.nz", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "New Zealand Network" },
  { tld: "org.nz", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "New Zealand Organizations" },
  { tld: "com.cn", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "China Commercial" },
  { tld: "net.cn", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "China Network" },
  { tld: "org.cn", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "China Organizations" },
  { tld: "com.tw", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Taiwan Commercial" },
  { tld: "net.tw", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Taiwan Network" },
  { tld: "com.hk", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Hong Kong Commercial" },
  { tld: "co.jp", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Japan Commercial" },
  { tld: "co.in", registrationPrice: 12.00, renewalPrice: 12.00, category: "cctld", description: "India Commercial" },
  { tld: "co.za", registrationPrice: 18.00, renewalPrice: 18.00, category: "cctld", description: "South Africa Commercial" },
  { tld: "com.mx", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Mexico Commercial" },
  { tld: "com.br", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Brazil Commercial" },
  { tld: "com.sg", registrationPrice: 22.00, renewalPrice: 22.00, category: "cctld", description: "Singapore Commercial" },
  { tld: "asia", registrationPrice: 8.49, renewalPrice: 17.50, category: "cctld", description: "Asia-Pacific region", isPromo: true, promoDuration: 1 },
];

const hostingPlans = [
  // ResellersPanel Plans
  {
    name: "Business",
    slug: "rp-business",
    provider: "resellerspanel",
    providerPlanId: "business",
    price: 3.50,
    renewalPrice: 3.50,
    currency: "USD",
    billingCycle: "monthly",
    description: "Perfect for small business websites with up to 5 domains",
    shortDescription: "5 domains, unlimited resources",
    features: ["5 Hosted Domains", "Unlimited Disk Space", "Unlimited Bandwidth", "20 MySQL Databases", "500 Email Accounts", "Free SSL", "Daily Backups", "ModSecurity Firewall", "1-Click Apps Installer"],
    highlights: ["5 Hosted Domains", "Unlimited Disk Space", "20 MySQL Databases"],
    diskSpace: "Unlimited",
    bandwidth: "Unlimited",
    websites: 5,
    emailAccounts: "500",
    databases: "20",
    ssl: true,
    backup: true,
    migration: true,
    sshAccess: false,
    dedicatedIp: false,
    websiteBuilder: true,
    oneClickInstaller: true,
    controlPanel: "Hepsia",
    isActive: true,
    isPopular: false,
    sortOrder: 1,
    category: "shared",
  },
  {
    name: "Corporate",
    slug: "rp-corporate",
    provider: "resellerspanel",
    providerPlanId: "corporate",
    price: 7.50,
    renewalPrice: 7.50,
    currency: "USD",
    billingCycle: "monthly",
    description: "For growing businesses needing more domains and resources",
    shortDescription: "15 domains, unlimited everything",
    features: ["15 Hosted Domains", "Unlimited Disk Space", "Unlimited Bandwidth", "Unlimited MySQL Databases", "Unlimited Email Accounts", "Free SSL", "Daily Backups", "ModSecurity Firewall", "SSH Access"],
    highlights: ["15 Hosted Domains", "Unlimited Disk Space", "Unlimited Databases"],
    diskSpace: "Unlimited",
    bandwidth: "Unlimited",
    websites: 15,
    emailAccounts: "Unlimited",
    databases: "Unlimited",
    ssl: true,
    backup: true,
    migration: true,
    sshAccess: true,
    dedicatedIp: false,
    websiteBuilder: true,
    oneClickInstaller: true,
    controlPanel: "Hepsia",
    isActive: true,
    isPopular: true,
    sortOrder: 2,
    category: "shared",
  },
  {
    name: "Enterprise",
    slug: "rp-enterprise",
    provider: "resellerspanel",
    providerPlanId: "enterprise",
    price: 12.50,
    renewalPrice: 12.50,
    currency: "USD",
    billingCycle: "monthly",
    description: "Unlimited hosting for large businesses and agencies",
    shortDescription: "Unlimited everything with dedicated IP",
    features: ["Unlimited Hosted Domains", "Unlimited Disk Space", "Unlimited Bandwidth", "Unlimited MySQL Databases", "Unlimited Email Accounts", "Free SSL", "Daily Backups", "ModSecurity Firewall", "SSH Access", "Dedicated IP"],
    highlights: ["Unlimited Domains", "Unlimited Disk Space", "Dedicated IP"],
    diskSpace: "Unlimited",
    bandwidth: "Unlimited",
    websites: -1,
    emailAccounts: "Unlimited",
    databases: "Unlimited",
    ssl: true,
    backup: true,
    migration: true,
    sshAccess: true,
    dedicatedIp: true,
    websiteBuilder: true,
    oneClickInstaller: true,
    controlPanel: "Hepsia",
    isActive: true,
    isPopular: false,
    sortOrder: 3,
    category: "shared",
  },

  // WebSouls Plans
  {
    name: "Basic",
    slug: "ws-basic",
    provider: "websouls",
    providerPlanId: "basic",
    price: 44.64,
    renewalPrice: 44.64,
    currency: "USD",
    billingCycle: "annually",
    description: "Entry-level hosting for personal websites and blogs",
    shortDescription: "1 website, 10GB storage",
    features: ["1 Website", "10GB Storage", "Unlimited Bandwidth", "Unlimited Email Accounts", "1 Database", "Virus & Spam Protection", "Free SSL", "Free Backup"],
    highlights: ["1 Website", "10GB Storage", "Free SSL"],
    diskSpace: "10GB",
    bandwidth: "Unlimited",
    websites: 1,
    emailAccounts: "Unlimited",
    databases: "1",
    ssl: true,
    backup: true,
    migration: true,
    sshAccess: false,
    dedicatedIp: false,
    websiteBuilder: false,
    oneClickInstaller: true,
    controlPanel: "cPanel",
    isActive: true,
    isPopular: false,
    sortOrder: 4,
    category: "shared",
  },
  {
    name: "Startup",
    slug: "ws-startup",
    provider: "websouls",
    providerPlanId: "startup",
    price: 59.46,
    renewalPrice: 59.46,
    currency: "USD",
    billingCycle: "annually",
    description: "For small businesses with multiple websites",
    shortDescription: "5 websites, 50GB storage",
    features: ["5 Websites", "50GB Storage", "Unlimited Bandwidth", "Unlimited Email Accounts", "5 Databases", "Virus & Spam Protection", "Free SSL", "Free Backup"],
    highlights: ["5 Websites", "50GB Storage", "5 Databases"],
    diskSpace: "50GB",
    bandwidth: "Unlimited",
    websites: 5,
    emailAccounts: "Unlimited",
    databases: "5",
    ssl: true,
    backup: true,
    migration: true,
    sshAccess: false,
    dedicatedIp: false,
    websiteBuilder: false,
    oneClickInstaller: true,
    controlPanel: "cPanel",
    isActive: true,
    isPopular: false,
    sortOrder: 5,
    category: "shared",
  },
  {
    name: "Grow",
    slug: "ws-grow",
    provider: "websouls",
    providerPlanId: "grow",
    price: 71.61,
    renewalPrice: 71.61,
    currency: "USD",
    billingCycle: "annually",
    description: "For growing businesses with high traffic websites",
    shortDescription: "100 websites, 100GB NVMe",
    features: ["100 Websites", "100GB NVMe Storage", "Unlimited Bandwidth", "Unlimited Email Accounts", "Unlimited Databases", "Virus & Spam Protection", "Free SSL", "Free Backup"],
    highlights: ["100 Websites", "100GB NVMe", "Unlimited Databases"],
    diskSpace: "100GB NVMe",
    bandwidth: "Unlimited",
    websites: 100,
    emailAccounts: "Unlimited",
    databases: "Unlimited",
    ssl: true,
    backup: true,
    migration: true,
    sshAccess: false,
    dedicatedIp: false,
    websiteBuilder: false,
    oneClickInstaller: true,
    controlPanel: "cPanel",
    isActive: true,
    isPopular: true,
    sortOrder: 6,
    category: "shared",
  },
  {
    name: "Digital",
    slug: "ws-digital",
    provider: "websouls",
    providerPlanId: "digital",
    price: 83.93,
    renewalPrice: 83.93,
    currency: "USD",
    billingCycle: "annually",
    description: "For digital agencies and large businesses",
    shortDescription: "150 websites, 150GB NVMe, AI Builder",
    features: ["150 Websites", "150GB NVMe Storage", "Unlimited Bandwidth", "Unlimited Email Accounts", "Unlimited Databases", "Virus & Spam Protection", "Free SSL", "Free Backup", "AI Website Builder"],
    highlights: ["150 Websites", "150GB NVMe", "AI Website Builder"],
    diskSpace: "150GB NVMe",
    bandwidth: "Unlimited",
    websites: 150,
    emailAccounts: "Unlimited",
    databases: "Unlimited",
    ssl: true,
    backup: true,
    migration: true,
    sshAccess: false,
    dedicatedIp: false,
    websiteBuilder: true,
    oneClickInstaller: true,
    controlPanel: "cPanel",
    isActive: true,
    isPopular: false,
    sortOrder: 7,
    category: "shared",
  },
  {
    name: "Business",
    slug: "ws-business",
    provider: "websouls",
    providerPlanId: "business",
    price: 158.57,
    renewalPrice: 158.57,
    currency: "USD",
    billingCycle: "annually",
    description: "Enterprise-grade hosting with all features",
    shortDescription: "200 websites, 250GB NVMe, SSH",
    features: ["200 Websites", "250GB NVMe Storage", "Unlimited Bandwidth", "Unlimited Email Accounts", "Unlimited Databases", "Virus & Spam Protection", "Free SSL", "Free Backup", "AI Website Builder", "SSH Access"],
    highlights: ["200 Websites", "250GB NVMe", "SSH Access"],
    diskSpace: "250GB NVMe",
    bandwidth: "Unlimited",
    websites: 200,
    emailAccounts: "Unlimited",
    databases: "Unlimited",
    ssl: true,
    backup: true,
    migration: true,
    sshAccess: true,
    dedicatedIp: false,
    websiteBuilder: true,
    oneClickInstaller: true,
    controlPanel: "cPanel",
    isActive: true,
    isPopular: false,
    sortOrder: 8,
    category: "shared",
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB");

    // Seed Domain TLDs
    await DomainTLD.deleteMany({});
    console.log("Cleared existing domain TLDs");

    const tldDocs = domainTLDs.map((tld, index) => {
      const margin = isCCTLD(tld.tld) ? MARGIN_CCTLD : MARGIN_GENERIC;
      return {
        tld: tld.tld,
        provider: "resellerspanel",
        registrationPrice: tld.registrationPrice,
        renewalPrice: tld.renewalPrice,
        transferPrice: tld.registrationPrice,
        currency: "USD",
        margin,
        finalPrice: applyMargin(tld.registrationPrice, margin),
        finalRenewalPrice: applyMargin(tld.renewalPrice, margin),
        description: tld.description,
        features: [],
        isActive: true,
        isPromo: tld.isPromo || false,
        promoPrice: tld.isPromo ? tld.registrationPrice : undefined,
        promoDuration: tld.promoDuration,
        category: tld.category,
        sortOrder: index + 1,
      };
    });

    await DomainTLD.insertMany(tldDocs);
    console.log(`Seeded ${tldDocs.length} domain TLDs`);

    // Seed Hosting Plans
    await HostingPlan.deleteMany({});
    console.log("Cleared existing hosting plans");

    const planDocs = hostingPlans.map((plan) => ({
      ...plan,
      finalPrice: applyMargin(plan.price, 15),
      finalRenewalPrice: applyMargin(plan.renewalPrice, 15),
    }));

    await HostingPlan.insertMany(planDocs);
    console.log(`Seeded ${planDocs.length} hosting plans`);

    console.log("Seed completed successfully");
    process.exit(0);
  } catch (error) {
    console.error("Seed failed:", error);
    process.exit(1);
  }
}

seed();
