import { Metadata } from "next";
import LegalPageView, { generateLegalMetadata } from "@/components/legal/legal-page-view";

export async function generateMetadata(): Promise<Metadata> {
  return generateLegalMetadata("copyright", "Copyright & Intellectual Property Policy");
}

export default function CopyrightPage() {
  return (
    <LegalPageView
      slug="copyright"
      fallbackTitle="Copyright & Intellectual Property Policy"
      fallbackContent={`
        <h2>1. Copyright Ownership</h2>
        <p>All content on the Wall-V website and services, including text, graphics, logos, icons, images, audio clips, digital downloads, data compilations, software, and code, is the property of Wall-V or its content suppliers and is protected by international copyright laws.</p>

        <h2>2. Intellectual Property Rights</h2>
        <p>Wall-V retains all intellectual property rights in its services, including:</p>
        <ul>
          <li>Website design, layout, and visual appearance</li>
          <li>AI models, algorithms, and training methodologies</li>
          <li>Software code, APIs, and technical documentation</li>
          <li>Brand names, trademarks, and service marks</li>
          <li>Marketing materials and content</li>
          <li>Proprietary processes and methodologies</li>
        </ul>

        <h2>3. Custom Development Work</h2>
        <p>For custom software development projects:</p>
        <ul>
          <li>Ownership of custom code transfers to the client upon full payment</li>
          <li>Wall-V retains rights to pre-existing tools, libraries, and frameworks used in development</li>
          <li>General knowledge and expertise gained during projects remains with Wall-V</li>
          <li>Specific IP terms are detailed in individual project agreements</li>
        </ul>

        <h2>4. AI-Generated Content</h2>
        <p>Content generated by our AI tools is subject to the following:</p>
        <ul>
          <li>Users receive a license to use AI-generated content as per their service agreement</li>
          <li>Wall-V does not claim copyright over AI-generated content created by users</li>
          <li>Users are responsible for ensuring AI outputs do not infringe third-party rights</li>
          <li>AI outputs should be verified for originality before commercial use</li>
        </ul>

        <h2>5. License to Use</h2>
        <p>Wall-V grants you a limited, non-exclusive, non-transferable, revocable license to access and use our services for personal or business purposes in accordance with these terms.</p>

        <h2>6. Restrictions</h2>
        <p>You may not:</p>
        <ul>
          <li>Reproduce, distribute, or create derivative works from our content without permission</li>
          <li>Use our trademarks, logos, or branding without written consent</li>
          <li>Reverse engineer, decompile, or disassemble our software</li>
          <li>Remove or alter any copyright or proprietary notices</li>
          <li>Use automated tools to scrape or download our content</li>
          <li>Claim ownership of our pre-existing intellectual property</li>
        </ul>

        <h2>7. Digital Millennium Copyright Act (DMCA)</h2>
        <p>If you believe that content on our services infringes your copyright, please send a DMCA takedown notice to legal@wall-v.com with:</p>
        <ul>
          <li>Description of the copyrighted work</li>
          <li>Location of the infringing material on our services</li>
          <li>Your contact information</li>
          <li>Statement of good faith belief</li>
          <li>Statement of accuracy under penalty of perjury</li>
        </ul>

        <h2>8. Open Source</h2>
        <p>Some components of our services may use open-source software. Such software is subject to its respective license terms, which are available upon request or in the applicable software documentation.</p>

        <h2>9. Trademarks</h2>
        <p>Wall-V, the Wall-V logo, and other marks are trademarks of Wall-V. You may not use these trademarks without prior written permission.</p>

        <h2>10. Contact</h2>
        <p>For IP-related inquiries, contact us at legal@wall-v.com.</p>
      `}
    />
  );
}
