import { NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/mongodb";
import Preview from "@/models/preview";
import Project from "@/models/project";
import { getAuthUser } from "@/lib/auth";
import { logError } from "@/lib/error-logger";

export async function GET(request: Request) {
  try {
    const user = await getAuthUser();
    if (!user || !["super-admin", "admin", "manager"].includes(user.role)) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    await connectToDatabase();
    const { searchParams } = new URL(request.url);
    const projectId = searchParams.get("projectId");
    const status = searchParams.get("status");
    const page = parseInt(searchParams.get("page") || "1");
    const limit = parseInt(searchParams.get("limit") || "20");

    const query: Record<string, unknown> = {};
    if (projectId) query.projectId = projectId;
    if (status && status !== "all") query.status = status;

    const total = await Preview.countDocuments(query);
    const previews = await Preview.find(query)
      .populate("projectId", "name slug")
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit)
      .lean();

    return NextResponse.json({
      success: true,
      data: previews,
      total,
      page,
      limit,
    });
  } catch (error) {
    await logError({
      level: "error",
      message: "Error fetching previews",
      source: "api/admin/previews",
      stack: error instanceof Error ? error.stack : undefined,
    });
    return NextResponse.json({ error: "Failed to fetch previews" }, { status: 500 });
  }
}

export async function PATCH(request: Request) {
  try {
    const user = await getAuthUser();
    if (!user || !["super-admin", "admin", "manager"].includes(user.role)) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = await request.json();
    const { previewId, action, expiresInMinutes, maxAccesses } = body;

    if (!previewId || !action) {
      return NextResponse.json({ error: "previewId and action are required" }, { status: 400 });
    }

    await connectToDatabase();

    const preview = await Preview.findById(previewId);
    if (!preview) {
      return NextResponse.json({ error: "Preview not found" }, { status: 404 });
    }

    switch (action) {
      case "revoke":
        preview.status = "revoked";
        preview.accessLog.push({
          timestamp: new Date(),
          event: "PREVIEW_REVOKED",
          details: `Revoked by ${user.email}`,
        });
        break;

      case "extend":
        if (expiresInMinutes) {
          preview.expiresAt = new Date(Date.now() + expiresInMinutes * 60 * 1000);
          preview.status = "active";
          preview.accessLog.push({
            timestamp: new Date(),
            event: "PREVIEW_EXTENDED",
            details: `Extended by ${user.email} for ${expiresInMinutes} minutes`,
          });
        }
        break;

      case "update-max-accesses":
        if (maxAccesses) {
          preview.maxAccesses = maxAccesses;
          preview.accessLog.push({
            timestamp: new Date(),
            event: "MAX_ACCESSES_UPDATED",
            details: `Updated by ${user.email} to ${maxAccesses}`,
          });
        }
        break;

      case "mark-paid":
        preview.paymentStatus = "paid";
        preview.status = "paid";
        preview.accessLog.push({
          timestamp: new Date(),
          event: "MARKED_AS_PAID",
          details: `Marked as paid by ${user.email}`,
        });
        // Update project payment status
        await Project.findByIdAndUpdate(preview.projectId, {
          paymentStatus: "paid",
          status: "in-progress",
        });
        break;

      case "regenerate":
        // Generate new token
        const crypto = await import("crypto");
        const newToken = crypto.randomBytes(32).toString("hex");
        const tokenHash = crypto.createHash("sha256").update(newToken).digest("hex");
        preview.token = newToken;
        preview.tokenHash = tokenHash;
        preview.status = "active";
        preview.accessCount = 0;
        preview.expiresAt = new Date(Date.now() + (expiresInMinutes || 5) * 60 * 1000);
        preview.accessLog.push({
          timestamp: new Date(),
          event: "PREVIEW_REGENERATED",
          details: `Regenerated by ${user.email}`,
        });
        break;

      default:
        return NextResponse.json({ error: "Invalid action" }, { status: 400 });
    }

    await preview.save();

    return NextResponse.json({
      success: true,
      data: {
        previewId: preview._id,
        status: preview.status,
        expiresAt: preview.expiresAt,
        token: action === "regenerate" ? preview.token : undefined,
      },
    });
  } catch (error) {
    await logError({
      level: "error",
      message: "Error updating preview",
      source: "api/admin/previews",
      stack: error instanceof Error ? error.stack : undefined,
    });
    return NextResponse.json({ error: "Failed to update preview" }, { status: 500 });
  }
}
