import { NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/mongodb";
import Project from "@/models/project";
import Client from "@/models/client";
import { generateDemoHTML } from "@/lib/demo-generator";
import { corsHeaders, handleOPTIONS } from "@/lib/cors";

// Dograh HTTP API Tool endpoint — called by the voice agent before ending the call
// Generates a demo/prototype and returns the preview URL

export async function OPTIONS() {
  return handleOPTIONS();
}

export async function POST(request: Request) {
  const headers = corsHeaders(request);
  try {
    const body = await request.json();
    console.log("[Generate Demo] Received:", JSON.stringify(body).slice(0, 500));

    // Dograh HTTP Tool sends the tool arguments directly
    const {
      client_name,
      client_email,
      client_phone,
      client_company,
      project_type,
      features,
      budget,
      timeline,
      description,
      selected_option,
    } = body;

    if (!client_name) {
      return NextResponse.json(
        { error: "client_name is required" },
        { status: 400, headers }
      );
    }

    await connectToDatabase();

    // Ensure client exists
    let client = null;
    if (client_email) {
      client = await Client.findOne({ email: client_email.toLowerCase().trim() });
    }
    if (!client && client_phone) {
      client = await Client.findOne({ phone: client_phone });
    }
    if (!client) {
      const placeholderEmail = client_email
        ? client_email.toLowerCase().trim()
        : `pending+${client_name.toLowerCase().replace(/\s+/g, ".")}${Date.now()}@wall-v.com`;
      client = await Client.create({
        name: client_name,
        email: placeholderEmail,
        phone: client_phone || undefined,
        company: client_company || undefined,
        type: client_company ? "business" : "individual",
        status: "prospect",
        source: "voice-agent",
        tags: ["voice-agent", "auto-created"],
        totalProjects: 0,
        totalSpent: 0,
        lastContact: new Date(),
      });
    }

    const demoId = `demo-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

    const demoRequirements = {
      projectType: project_type || "website",
      name: client_name,
      email: client_email || "",
      features: features || [],
      budget: budget || "1000",
      timeline: timeline || "",
      description: description || "",
      selectedOption: selected_option || "",
      company: client_company || "",
      phone: client_phone || "",
    };

    const demoHTML = generateDemoHTML(demoRequirements, demoId);

    // Parse budget for quote
    const budgetNum = parseInt(String(budget).replace(/[^0-9]/g, "")) || 1000;

    const safeEmail = client_email
      ? client_email.toLowerCase().trim()
      : `pending+${client_name.toLowerCase().replace(/\s+/g, ".")}${Date.now()}@wall-v.com`;

    const project = await Project.create({
      name: `${project_type || "Project"} — ${client_name}`,
      slug: `${(project_type || "project").toLowerCase().replace(/\s+/g, "-")}-${Date.now()}`,
      title: `${project_type || "Project"} — ${client_name}`,
      description: description || `Voice agent generated demo for ${client_name}`,
      client: {
        name: client_name,
        email: safeEmail,
        phone: client_phone || "",
        company: client_company || "",
      },
      status: "demo",
      priority: "medium",
      budget: budgetNum,
      currency: "USD",
      progress: 0,
      milestones: [
        { name: "Discovery & Planning", description: "Requirements gathering and project planning", status: "pending" },
        { name: "Design", description: "UI/UX design and prototyping", status: "pending" },
        { name: "Development", description: "Core implementation", status: "pending" },
        { name: "Testing", description: "Quality assurance and bug fixes", status: "pending" },
        { name: "Launch", description: "Deployment and go-live", status: "pending" },
      ],
      requirements: {
        projectType: project_type || "website",
        features: features || [],
        budget: budget ? `$${budgetNum.toLocaleString()}` : "",
        timeline: timeline || "",
      },
      demoHTML,
      demoId,
      quote: {
        min: budgetNum,
        max: Math.round(budgetNum * 1.5),
        currency: "USD",
      },
      tags: ["voice-agent", "dograh", project_type || "website"].filter(Boolean),
      notes: `Generated by voice agent during call.`,
    });

    // Update client
    client.totalProjects = (client.totalProjects || 0) + 1;
    client.lastContact = new Date();
    await client.save();

    const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://wall-v.com";
    const previewUrl = `${appUrl}/preview/${project._id}`;
    const checkoutUrl = `${appUrl}/checkout/${project._id}`;

    console.log("[Generate Demo] Created:", { projectId: project._id, demoId, previewUrl });

    // Return in a format Dograh can use as tool output
    return NextResponse.json({
      success: true,
      project_id: project._id.toString(),
      demo_id: demoId,
      preview_url: previewUrl,
      checkout_url: checkoutUrl,
      project_name: project.name,
      budget_range: `$${budgetNum.toLocaleString()} - $${Math.round(budgetNum * 1.5).toLocaleString()}`,
      message: `Demo created successfully for ${client_name}. Preview URL: ${previewUrl}`,
    }, { headers });
  } catch (error) {
    console.error("[Generate Demo] Error:", error);
    return NextResponse.json(
      { error: "Failed to generate demo" },
      { status: 500, headers }
    );
  }
}

export async function GET() {
  return NextResponse.json({ status: "ok", endpoint: "voice-agent/generate-demo" });
}
