import { NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/mongodb";
import ServicePrice from "@/models/service-price";
import { getAuthUser } from "@/lib/auth";

const DEFAULT_PRICES = [
  {
    serviceKey: "web-development",
    name: "Web Development",
    category: "development",
    description: "Custom web applications built with React, Next.js, Node.js",
    type: "starting-at" as const,
    basePrice: 1999,
    tiers: [
      { name: "Basic", price: 1999, features: ["Up to 5 pages", "Responsive design", "Contact form", "Basic SEO", "1 month support"] },
      { name: "Standard", price: 4999, features: ["Up to 15 pages", "Custom design", "CMS integration", "SEO optimization", "3 months support"] },
      { name: "Premium", price: 9999, features: ["Unlimited pages", "Full-stack app", "Database integration", "Admin dashboard", "6 months support"] },
    ],
    features: ["Business websites", "Custom web applications", "SaaS platforms", "E-commerce websites", "Client portals", "Admin dashboards"],
    technology: ["Next.js", "React", "TypeScript", "Node.js", "MongoDB"],
    estimatedHours: { min: 40, max: 400 },
    estimatedWeeks: { min: 2, max: 16 },
    active: true,
    displayOrder: 1,
    agentVisible: true,
    agentDescription: "Custom web applications — business websites, dashboards, e-commerce, SaaS platforms. Packages from $1,999 (Basic) to $9,999 (Premium). Built with React, Next.js, TypeScript, Node.js, and MongoDB.",
  },
  {
    serviceKey: "mobile-apps",
    name: "Mobile Applications",
    category: "development",
    description: "Native and cross-platform mobile apps for iOS and Android",
    type: "starting-at" as const,
    basePrice: 4999,
    tiers: [
      { name: "MVP", price: 4999, features: ["Cross-platform (React Native)", "Core features", "Push notifications", "App Store submission"] },
      { name: "Standard", price: 9999, features: ["Cross-platform + native feel", "Offline support", "API integrations", "3 months support"] },
      { name: "Premium", price: 19999, features: ["Native iOS + Android", "Custom animations", "Real-time features", "6 months support"] },
    ],
    features: ["Cross-platform apps (React Native / Flutter)", "Native iOS and Android", "Offline-first architecture", "Push notifications", "App Store deployment"],
    technology: ["React Native", "Flutter", "iOS", "Android"],
    estimatedHours: { min: 120, max: 800 },
    estimatedWeeks: { min: 4, max: 32 },
    active: true,
    displayOrder: 2,
    agentVisible: true,
    agentDescription: "Native and cross-platform mobile apps for iOS and Android. MVP from $4,999, Standard $9,999, Premium $19,999. Built with React Native or Flutter.",
  },
  {
    serviceKey: "ecommerce",
    name: "E-Commerce Solutions",
    category: "development",
    description: "Full e-commerce stores with payment processing, inventory, and analytics",
    type: "starting-at" as const,
    basePrice: 3999,
    tiers: [
      { name: "Starter", price: 3999, features: ["Up to 50 products", "Payment processing (Stripe)", "Order management", "Basic analytics"] },
      { name: "Growth", price: 7999, features: ["Up to 500 products", "Multi-payment gateways", "Inventory tracking", "Discount codes", "Email integration"] },
      { name: "Enterprise", price: 14999, features: ["Unlimited products", "Custom checkout", "ERP integration", "B2B pricing", "Priority support"] },
    ],
    features: ["Product management", "Payment processing", "Order management", "Inventory tracking", "Analytics dashboard"],
    technology: ["Next.js", "Stripe", "PayPal", "MongoDB"],
    estimatedHours: { min: 100, max: 500 },
    estimatedWeeks: { min: 4, max: 16 },
    active: true,
    displayOrder: 3,
    agentVisible: true,
    agentDescription: "Complete e-commerce solutions — Starter $3,999 (50 products), Growth $7,999 (500 products), Enterprise $14,999 (unlimited). Payment processing, inventory, analytics included.",
  },
  {
    serviceKey: "crm-systems",
    name: "CRM Systems",
    category: "development",
    description: "Customer relationship management with lead scoring and pipeline",
    type: "starting-at" as const,
    basePrice: 3499,
    features: ["Lead management", "Pipeline tracking", "Client communication", "Invoicing integration", "Reporting dashboards"],
    technology: ["Next.js", "React", "Node.js", "MongoDB"],
    estimatedHours: { min: 80, max: 500 },
    estimatedWeeks: { min: 4, max: 20 },
    active: true,
    displayOrder: 4,
    agentVisible: true,
    agentDescription: "Custom CRM systems from $3,499 — lead management, sales pipeline tracking, client communication, invoicing integration, and real-time reporting dashboards.",
  },
  {
    serviceKey: "erp-systems",
    name: "ERP Systems",
    category: "development",
    description: "Enterprise resource planning tailored to your business",
    type: "starting-at" as const,
    basePrice: 7999,
    features: ["Finance modules", "HR management", "Inventory tracking", "Real-time dashboards", "Third-party integrations"],
    technology: ["Next.js", "Node.js", "MongoDB", "REST APIs"],
    estimatedHours: { min: 200, max: 1000 },
    estimatedWeeks: { min: 8, max: 40 },
    active: true,
    displayOrder: 5,
    agentVisible: true,
    agentDescription: "Enterprise resource planning systems from $7,999 — finance, HR, inventory management, real-time dashboards, and third-party integrations.",
  },
  {
    serviceKey: "saas-development",
    name: "SaaS Platform Development",
    category: "development",
    description: "Custom SaaS platforms with multi-tenancy, billing, and admin",
    type: "starting-at" as const,
    basePrice: 14999,
    features: ["Multi-tenant architecture", "Subscription billing (Stripe)", "Role-based access", "Admin dashboard", "API & integrations"],
    technology: ["Next.js", "Node.js", "MongoDB", "Stripe"],
    estimatedHours: { min: 300, max: 1200 },
    estimatedWeeks: { min: 12, max: 40 },
    active: true,
    displayOrder: 6,
    agentVisible: true,
    agentDescription: "Custom SaaS platforms from $14,999 — multi-tenancy, subscription billing, role-based access, admin dashboard, API integrations. Full MVP to production.",
  },
  {
    serviceKey: "ai-chatbot",
    name: "AI Chatbot Development",
    category: "ai-automation",
    description: "Custom AI chatbots trained on your business data",
    type: "starting-at" as const,
    basePrice: 2499,
    tiers: [
      { name: "Basic", price: 2499, features: ["Rule-based + AI hybrid", "FAQ training", "Website widget", "Basic analytics"] },
      { name: "Professional", price: 4999, features: ["RAG architecture", "Custom knowledge base", "CRM integration", "Multi-language", "Analytics dashboard"] },
      { name: "Enterprise", price: 9999, features: ["Fine-tuned LLM", "Multi-system integration", "Human-in-the-loop", "Custom workflows", "Priority support"] },
    ],
    features: ["Custom AI training", "Knowledge base integration", "Multi-language", "WhatsApp/Telegram", "Analytics"],
    technology: ["OpenAI", "LangChain", "Vector DB", "Next.js"],
    estimatedHours: { min: 60, max: 300 },
    estimatedWeeks: { min: 2, max: 10 },
    active: true,
    displayOrder: 10,
    agentVisible: true,
    agentDescription: "Custom AI chatbots from $2,499 (Basic) to $9,999 (Enterprise). Trained on your business data — website widget, CRM integration, multi-language support. Pays for itself in 3–6 months vs. SaaS chatbot platforms ($29–$2,999/mo).",
  },
  {
    serviceKey: "voice-agent",
    name: "AI Voice Agent Development",
    category: "ai-automation",
    description: "AI voice agents for phone support, sales, and scheduling",
    type: "starting-at" as const,
    basePrice: 3999,
    tiers: [
      { name: "Starter", price: 3999, features: ["Single voice agent", "Phone answering", "Basic call routing", "Call transcripts"] },
      { name: "Professional", price: 7999, features: ["Multi-agent setup", "CRM integration", "Appointment booking", "Call recording & analytics"] },
      { name: "Enterprise", price: 14999, features: ["Custom voice cloning", "Multi-language", "Complex workflows", "API integrations", "Dedicated support"] },
    ],
    features: ["Natural voice conversations", "Call handling", "CRM integration", "Call recording", "Multi-language"],
    technology: ["Dograh", "ElevenLabs", "Twilio", "WebRTC"],
    estimatedHours: { min: 80, max: 400 },
    estimatedWeeks: { min: 3, max: 12 },
    active: true,
    displayOrder: 11,
    agentVisible: true,
    agentDescription: "AI voice agents from $3,999 (Starter) to $14,999 (Enterprise). Handle phone calls 24/7 — customer support, appointment booking, sales follow-ups. vs. hiring a receptionist ($2,500–$4,000/mo) or SaaS voice platforms ($0.07–$0.20/min).",
  },
  {
    serviceKey: "ai-automation",
    name: "AI Process Automation",
    category: "ai-automation",
    description: "Automate repetitive business processes with AI workflows",
    type: "starting-at" as const,
    basePrice: 1999,
    features: ["Workflow automation", "Data extraction", "Document processing", "Integration with existing tools", "Custom AI models"],
    technology: ["Python", "LangChain", "APIs", "ML"],
    estimatedHours: { min: 40, max: 200 },
    estimatedWeeks: { min: 2, max: 8 },
    active: true,
    displayOrder: 12,
    agentVisible: true,
    agentDescription: "AI process automation from $1,999 — automate repetitive tasks, data extraction, document processing, and custom workflows. Free up your team for high-value work.",
  },
  {
    serviceKey: "hosting-basic",
    name: "Basic Hosting",
    category: "hosting",
    description: "Entry-level hosting for personal sites and blogs",
    type: "fixed" as const,
    basePrice: 3.99,
    currency: "USD",
    features: ["1 Website", "5GB Storage", "Free SSL", "99.9% Uptime"],
    active: true,
    displayOrder: 20,
    agentVisible: true,
    agentDescription: "Basic hosting — $3.99/month. 1 website, 5GB storage, free SSL. Cheaper than Wix ($17/mo) and Squarespace ($16/mo).",
  },
  {
    serviceKey: "hosting-business",
    name: "Business Hosting",
    category: "hosting",
    description: "Hosting for growing businesses with multiple sites",
    type: "fixed" as const,
    basePrice: 9.99,
    currency: "USD",
    features: ["10 Websites", "25GB Storage", "Daily Backups", "Free SSL", "99.9% Uptime"],
    active: true,
    displayOrder: 21,
    agentVisible: true,
    agentDescription: "Business hosting — $9.99/month. 10 websites, 25GB storage, daily backups. Half the price of Wix Core ($29/mo).",
  },
  {
    serviceKey: "hosting-cloud",
    name: "Cloud Hosting",
    category: "hosting",
    description: "High-performance cloud hosting for demanding sites",
    type: "fixed" as const,
    basePrice: 16.99,
    currency: "USD",
    features: ["Unlimited Sites", "50GB Storage", "CDN", "Free SSL", "99.9% Uptime"],
    active: true,
    displayOrder: 22,
    agentVisible: true,
    agentDescription: "Cloud hosting — $16.99/month. Unlimited sites, 50GB storage, CDN. Half the price of Wix Business ($39/mo).",
  },
  {
    serviceKey: "hosting-wordpress",
    name: "WordPress Hosting",
    category: "hosting",
    description: "Optimized hosting for WordPress sites",
    type: "fixed" as const,
    basePrice: 6.99,
    currency: "USD",
    features: ["1 Website", "10GB Storage", "Auto Updates", "Free SSL"],
    active: true,
    displayOrder: 23,
    agentVisible: true,
    agentDescription: "WordPress hosting — $6.99/month. 1 website, 10GB storage, auto updates, free SSL.",
  },
  {
    serviceKey: "hosting-reseller",
    name: "Reseller Hosting",
    category: "hosting",
    description: "White-label hosting for agencies and resellers",
    type: "fixed" as const,
    basePrice: 29.99,
    currency: "USD",
    features: ["50 Accounts", "100GB Storage", "White Label", "Free SSL"],
    active: true,
    displayOrder: 24,
    agentVisible: true,
    agentDescription: "Reseller hosting — $29.99/month. 50 accounts, 100GB storage, white-label branding for agencies.",
  },
  {
    serviceKey: "hosting-email",
    name: "Email Hosting",
    category: "hosting",
    description: "Professional email hosting with custom domain",
    type: "fixed" as const,
    basePrice: 1.99,
    currency: "USD",
    features: ["5 Accounts", "5GB Storage", "Custom Domain", "Spam Protection"],
    active: true,
    displayOrder: 25,
    agentVisible: true,
    agentDescription: "Email hosting — $1.99/month. 5 email accounts, 5GB storage, custom domain, spam protection.",
  },
  {
    serviceKey: "domain-registration",
    name: "Domain Registration",
    category: "domains",
    description: "Register and manage domain names",
    type: "starting-at" as const,
    basePrice: 9.99,
    currency: "USD",
    features: [".com", ".net", ".org", ".pk", ".io", ".dev", ".app", ".co"],
    active: true,
    displayOrder: 30,
    agentVisible: true,
    agentDescription: "Domain registration from $9.99/year. Available: .com, .net, .org, .pk, .io, .dev, .app, .co.",
  },
  {
    serviceKey: "digital-marketing",
    name: "Digital Marketing",
    category: "marketing",
    description: "SEO, PPC, social media, and analytics",
    type: "starting-at" as const,
    basePrice: 999,
    tiers: [
      { name: "Starter", price: 999, features: ["Keyword research", "On-page SEO", "Monthly reporting"] },
      { name: "Growth", price: 1999, features: ["Everything in Starter", "Google Ads", "Social media management", "Content strategy"] },
      { name: "Enterprise", price: 3999, features: ["Everything in Growth", "Multi-channel campaigns", "Conversion optimization", "Dedicated strategist"] },
    ],
    features: ["Search engine optimization (SEO)", "Google Ads and Meta Ads", "Social media strategy", "Analytics setup", "Email marketing"],
    active: true,
    displayOrder: 35,
    agentVisible: true,
    agentDescription: "Digital marketing from $999/month (Starter) to $3,999/month (Enterprise). SEO, Google Ads, Meta Ads, social media strategy, analytics, and email marketing.",
  },
  {
    serviceKey: "uiux-design",
    name: "UI/UX Design",
    category: "design",
    description: "User interface and experience design",
    type: "starting-at" as const,
    basePrice: 1499,
    features: ["Wireframing and prototyping", "Brand identity", "Design systems", "Usability testing"],
    technology: ["Figma", "Adobe XD", "Tailwind CSS"],
    estimatedHours: { min: 40, max: 200 },
    estimatedWeeks: { min: 2, max: 8 },
    active: true,
    displayOrder: 40,
    agentVisible: true,
    agentDescription: "UI/UX design from $1,499 — wireframing, prototyping, brand identity, design systems, and usability testing. Built in Figma.",
  },
  {
    serviceKey: "technical-consulting",
    name: "Technical Consulting",
    category: "consulting",
    description: "Expert technical consulting for your digital projects",
    type: "hourly" as const,
    hourlyRate: 175,
    features: ["Architecture review", "Technology selection", "Performance audit", "Security review", "Team mentoring"],
    technology: ["Various"],
    estimatedHours: { min: 5, max: 50 },
    estimatedWeeks: { min: 1, max: 4 },
    active: true,
    displayOrder: 45,
    agentVisible: true,
    agentDescription: "Technical consulting at $175/hour — architecture reviews, technology selection, performance audits, security reviews, and team mentoring.",
  },
  {
    serviceKey: "devops",
    name: "DevOps & Cloud",
    category: "consulting",
    description: "Cloud infrastructure setup, CI/CD, and DevOps consulting",
    type: "hourly" as const,
    hourlyRate: 150,
    features: ["AWS/GCP/Azure setup", "CI/CD pipelines", "Docker/Kubernetes", "Monitoring & alerting", "Security audit"],
    technology: ["AWS", "GCP", "Docker", "Kubernetes", "Terraform"],
    estimatedHours: { min: 20, max: 200 },
    estimatedWeeks: { min: 1, max: 8 },
    active: true,
    displayOrder: 46,
    agentVisible: true,
    agentDescription: "DevOps consulting at $150/hour — cloud setup, CI/CD pipelines, containerization, monitoring, and infrastructure automation.",
  },
];

export async function POST() {
  try {
    let user;
    try {
      user = await getAuthUser();
    } catch (authErr) {
      const msg = authErr instanceof Error ? authErr.message : String(authErr);
      return NextResponse.json({ error: "Auth failed", details: msg }, { status: 401 });
    }
    if (!user || !["super-admin", "admin"].includes(user.role)) {
      return NextResponse.json({ error: "Unauthorized", details: user ? `role: ${user.role}` : "no user" }, { status: 401 });
    }

    await connectToDatabase();

    let created = 0;
    let updated = 0;

    for (const price of DEFAULT_PRICES) {
      try {
        const existing = await ServicePrice.findOne({ serviceKey: price.serviceKey });
        if (existing) {
          await ServicePrice.updateOne({ serviceKey: price.serviceKey }, { $set: price });
          updated++;
        } else {
          await ServicePrice.create(price);
          created++;
        }
      } catch (itemErr) {
        console.error(`Seed item failed for ${price.serviceKey}:`, itemErr);
      }
    }

    return NextResponse.json({
      success: true,
      message: `Seeding complete: ${created} created, ${updated} updated`,
      created,
      updated,
    });
  } catch (error) {
    console.error("Seed error:", error);
    const msg = error instanceof Error ? error.message : String(error);
    return NextResponse.json({ error: "Seed failed", details: msg }, { status: 500 });
  }
}
