import { Metadata } from "next";
import LegalPageView, { generateLegalMetadata, getLegalPageData } from "@/components/legal/legal-page-view";

export const dynamic = "force-dynamic";

export async function generateMetadata(): Promise<Metadata> {
  return generateLegalMetadata("accessibility", "Accessibility Statement");
}

const FALLBACK_CONTENT = `
  <h2>Our Commitment to Accessibility</h2>
  <p>Wall-V is committed to ensuring digital accessibility for people with disabilities. We are continually improving the user experience for everyone and applying the relevant accessibility standards.</p>

  <h2>Standards We Follow</h2>
  <p>We strive to conform to the Web Content Accessibility Guidelines (WCAG) 2.1 Level AA. These guidelines explain how to make web content more accessible for people with disabilities and more user-friendly for everyone.</p>

  <h2>Measures Taken</h2>
  <ul>
    <li>Semantic HTML structure with proper heading hierarchy</li>
    <li>Alt text for all meaningful images</li>
    <li>Keyboard navigation support for all interactive elements</li>
    <li>Sufficient color contrast ratios</li>
    <li>Resizable text without loss of functionality</li>
    <li>Focus indicators for keyboard navigation</li>
    <li>ARIA labels and landmarks where appropriate</li>
    <li>Form labels and error messages associated with inputs</li>
  </ul>

  <h2>AI-Generated Content</h2>
  <p>Some content on our website is generated by AI tools. While we review AI-generated content for accuracy and accessibility, we acknowledge that AI-generated content may not always meet accessibility standards perfectly. We work to improve this continuously.</p>

  <h2>Known Limitations</h2>
  <p>We are aware of some accessibility limitations:</p>
  <ul>
    <li>Some older PDF documents may not be fully accessible</li>
    <li>Third-party embedded content may not meet our accessibility standards</li>
    <li>Some interactive data visualizations may have limited accessibility</li>
  </ul>

  <h2>Feedback</h2>
  <p>We welcome your feedback on the accessibility of our website. If you encounter accessibility barriers, please contact us at accessibility@wall-v.com. We will respond to your feedback within 5 business days.</p>

  <h2>Compatibility</h2>
  <p>We aim to be compatible with the latest versions of major browsers including Chrome, Firefox, Safari, and Edge. Our website is designed to work on both desktop and mobile devices.</p>

  <h2>Assessment Approach</h2>
  <p>Wall-V assesses accessibility through a combination of automated testing tools and manual testing by our development team.</p>
`;

export default async function AccessibilityPage() {
  const data = await getLegalPageData("accessibility", "Accessibility Statement", FALLBACK_CONTENT);
  return <LegalPageView data={data} />;
}
